### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by DionTimmermann**
This pull-request contains performance improvements for different functions. Overall they reduce the run time for my test case (OSM calibration with deembedding) from 148sec to 93 sec, so a 37% reduction in run time. 

This pull-request shold not change the behaviour of any function. For me, all tests in https://github.com/DionTimmermann/metas-unclib-matlab-wrapper pass.

The most imporant improvement is https://github.com/wollmich/metas-unclib-matlab-wrapper/commit/82b23ae416d858c9443196c081b05a2971ec2187 . 

I also tried to improve the performance of subsref (the most compute-intensive part of my test), but speed-ups in that function resulted in more overhead in other functions, resulting in a negligible net gain. However, I might try some other improvements in the future.

### CODE REVIEW

**Comment by wollmich** [comment]
> The most imporant improvement is https://github.com/wollmich/metas-unclib-matlab-wrapper/commit/82b23ae416d858c9443196c081b05a2971ec2187 .

I've one comment see https://github.com/wollmich/metas-unclib-matlab-wrapper/commit/82b23ae416d858c9443196c081b05a2971ec2187#r68687177.

**Comment by DionTimmermann** [comment]
Good Idea, I did not try moving `UncHelper()` into a privat static property! Actually, I think it would be best if each generic class that is needed in frequently called functions would only be created once in matlab. That would save quite a lot of time. I will do some tests in the next days.

I also found why my changes to subsref seemed to not result in a speed up (the test case rarely called the improved parts) and have several new ideas how to speed up the function.

**Comment by DionTimmermann** [comment]
And there I was confused by matlab's [NET.createGeneric](https://de.mathworks.com/help/matlab/ref/net.creategeneric.html) and [NET.GenericClass](https://de.mathworks.com/help/matlab/ref/net.genericclass-class.html). `NET.createGeneric` creates instances of specialized .NET generic types - these instances of cause cannot just be created once.

Still, I will try making `UncHelper()` into a privat static property.

**Comment by DionTimmermann** [comment]
I created the private constant (i.e. static) property `UncHelper`, which saved about 20% of run time in the following example:
```MATLAB
profile on
for ii=1:10000
    LinProp(rand(3, 3));
end
profile viewer
```
When the constant is first initialized, the appropriate assemblies have to be loaded. To achieve that, the value of `UncHelper` is assigned by `UncHelperFactory()` - however I am not sure if that name is misleading - there is no factory pattern after all.

As `UncHelperFactory()` loads the assemblies, the constructor does not have to call `UncPropLoadNETAssemblies()` anymore, which saves some additional time. I inserted a comment in the constructor to explain why the assemblies do not have to be loaded - but I am on the fence if the comment is usefull.

**Comment by DionTimmermann** [comment]
I was also able to reduce the runtime of subsref by about 50%. Now, almost 90% of the function's runtime is spent in uncLib functions. 

The changes to the method are quite extensive. I changed almost every line of the method. Do you prefer me to add these changes to this pull-request or open a new one?

**Comment by wollmich** [comment]
> Do you prefer me to add these changes to this pull-request or open a new one?

Yes please create a new pull request for your `subsref` improvements.

**Comment by DionTimmermann** [comment]
Ok, I created separate pull requests for subsref() and subsasgn().

I also added a a commit to this pull request with some simple further improvemts to `size()`.

At the moment, the only possible relevant improvement that I am aware of is the following code block at the end of the constructor:
```MATLAB
            % Ensure arrays are internally always stored as matrices.
            if LinProp.IsArrayNet(obj.NetObject)
                if obj.NetObject.ndims == 1
                    obj.NetObject.Reshape(int32([obj.NetObject.numel 1]));
                end
            end 
```
The calls to `IsArrayNet()` and `obj.NetObject.ndims` are quite expensive and this test is probably never true when initializing a scalar. But any solution I can think of would be bodged, so I would leave it as is. Together with #49 and #50 this pull-request more than doubles the speed of unc calculations for my tests. For me, that is enough for now.

**Comment by DionTimmermann** [comment]
https://github.com/DionTimmermann/metas-unclib-matlab-wrapper-tests/commit/40942d1771915152cfda400c99938a5ff6af05e6 added tests for newly discovered discrepancies between the behaviour of double variables and unc variables. This branch (and the main branch) fail these new tests tests. They are fixed in/by #50 .

**Pull request merged**
