### PR TITLE
Added diff

### PR DESCRIPTION
**Pull request by DionTimmermann**
I needed the diff() function, i.e. diff(x) = x(2:end)-x(1:end-1), so I implemented it. 

From what I could see, the uncLib does not contain a diff() function. An implemetation using the subtract methods from the uncLib also seemed to not be that helpful, as I first would have to create two copies of the matrix (2:end and 1:end-1). Instead, the implementation presented here only calls subsref and the minus operator and therefore reuses several existing methods.

diff() requires the bugfix to subsref commited in #6 .

### CODE REVIEW

**Comment by DionTimmermann** [comment]
The tests can be found in https://github.com/DionTimmermann/metas-unclib-matlab-wrapper-tests/blob/main/unit_tests_diff.m .

**Comment by wollmich** [comment]
Can you give me an example where you would need `diff()` with uncertainty numbers?

**Comment by DionTimmermann** [comment]
The more I think about it, the less I beliebe I really need it. Still, here is a minimal example, based on my original problem.

We have time domain data from an osciloscope, which we want to analyze. These consist of a linearly spaced vector `t` for the sapling times and a vector `V` for the voltages. We want to account for the osciloscope's amplitude uncertainty, but also the sampling time uncertainty, i.e. if the sample was taken at the correct time. Adding the sampling time uncercatainty to the vector `t` would make the subsequent analysis difficult, as we also want to analyze the data in the frequency domain. Therefore, we wanted to map the sampling time uncertainty onto the voltage by multiplying the sampling time uncertainty with the slope of each datapoint.

When I wrote this function, I believed the slope should be based on the voltages with amplitude uncertainty, but the more I think about it, the more I believe the slope should only be calculated, based on the raw voltage values.

A minimal examples can be found below:
```
%%
clear;
close all;

% Generate a simple periodic time domain signal for this example
t = linspace(0, 1e-7, 1e3);
V = 0.4 * sin(2*pi*t/t(end));
                         
uV = 0.001; % Amplitude uncertainty in V
ut = 0.5e-12; % Sampling time uncertainty in s
dt = t(2)-t(1);

fprintf('%s: Created time domain data.\n', datestr(clock));
fprintf('Sampling time uncertainty is %f.1 the sampling interval.\n', ut/dt);


%% Add Uncertainties

unc = @LinProp;

% dV is the derivation/slope of V. It is used below to map the sampling
% time uncertainty onto the Voltage.
dV = mean([diff([V(end) V]); diff([V V(1)])], 1); % Derivation / slope averaged for left and right side.

V = arrayfun(@(x, i, t) unc(x, uV, sprintf('Amplitude uncertainty, sample %i, t=%f', i, t)), V, 1:numel(V), t);
ut = arrayfun(@(x, i, t) unc(0, ut, sprintf('Sampling time uncertainty, sample %i, t=%f', i, t)), V, 1:numel(V), t);

% When I wrote the diff() function for unc variables, I beliebed dV should
% be calculated here, i.e. dV should account for the uncertainty of V.
% dV = mean([diff([V(end) V]); diff([V V(1)])], 1); % Derivation / slope averaged for left and right side.

V = V + dV.*(ut/dt); % Add sampling time uncertainty

clear ut dV
fprintf('%s: Added uncertainties.\n', datestr(clock));

%% Plot Time Domain Data

figure();
subplot(2, 1, 1);
    plot(t * 1e9, double(V));
    ylabel('Voltage / [V]');
    xlabel('Time / ns');
subplot(2, 1, 2);
    plot(t * 1e9, get_stdunc(V));
    ylabel('Std. Uncertainty / [V]');
    xlabel('Time / ns');

```

**Comment by DionTimmermann** [comment]
And to be clear: I would not be offended, if you did not want to include this function in the uncLib. I do not know of a usecase for diff() in the context of VNAs and adding the function would increase the amount of code to test/maintain afterall.

**Comment by wollmich** [comment]
I will close this pull request, if there is a need for `diff()` at a later time, we can reopen this pull request.

**Pull request closed without merging**
